jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet build

  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover
  
  analyze:
    needs: [build, test]
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2.3.1
      - run: git fetch --unshallow
      - run: dotnet tool install --global dotnet-sonarscanner
      - run: |
          dotnet sonarscanner begin -o:'button-pushing-fingers' -k:'bpfp2coal'
          dotnet build
          dotnet test -p:CollectCoverage=true -p:CoverletOutputFormat=opencover --logger trx
          dotnet sonarscanner end
  
  # package:
  #   env:
  #     DOCKER_LOGIN: ${{ secrets.DOCKER_LOGIN }}
  #     DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
  #   needs: [analyze]
  #   runs-on: ubuntu-18.04
  #   steps:
  #     - uses: actions/checkout@v2.3.1
  #     - run: docker login --username ${DOCKER_LOGIN} --password ${DOCKER_TOKEN}
  #     - run: docker image build -f dockerfile -t devopsci .
  #     - run: docker image tag devopsci bpfrev/devopsci
  #     - run: docker image push bpfrev/devopsci
  #     - run: docker logout

name: cibuild
on: push